title: Paramesh Gunasekaran
url: "cv.paramg.com"
baseurl: ""
description: "Curriculum Vitae of Paramesh Gunasekaran"
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar
analytics: ""

sass:
  sass_dir: _sass
  style: compressed

compress-site: yes
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false