name: publish
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: docker run --rm -v $PWD:/srv/jekyll -e "JEKYLL_ENV=production" jekyll/builder:3.8 jekyll build

      - name: deploy
        run: docker run --rm -v $PWD:/aws -e "AWS_EC2_METADATA_DISABLED=true" -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" amazon/aws-cli:latest s3 cp /aws/_site s3://cv.paramg.com/ --recursive
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
